describe('Shopping site Emag', () => {
        
    it('Verify a TV and an accessory for the TV', () => {
        cy.visit('https://www.emag.ro/')
        cy.get('li[data-id="190"]').click()
        cy.get('a').contains('Televizoare & accesorii').click()
        cy.get('li > a').contains('Televizoare').click()
        cy.get('a[data-name="Samsung"]').click()
        cy.wait(800)
        cy.get('.star-rating.star-rating-read.rated-3.star-rating-sm').click()
        cy.wait(800)
        cy.get('a[data-name="In Stoc"]').click()
        cy.wait(800)
        cy.get('a[data-name="QLED"]').click()
        cy.wait(800)
        cy.get('button > span').contains('Cele mai populare').click()
        cy.get('li > a').contains('Pret descrescator').click({force:true})
        cy.wait(600)
        cy.get('div[id=card_grid] > div').eq(0).click(100, 100)
        cy.get('button[data-test="main-add-to-cart-button"]').click()
        cy.wait(600)
        cy.get('button[data-test="atc-modal-close"]').click()

        cy.get('ol > li > a').contains('Televizoare & accesorii').click()
        cy.get('li > a').contains('Accesorii TV').click()
        cy.get('a[data-name="Samsung"]').click()
        cy.wait(800)
        cy.get('.star-rating.star-rating-read.rated-3.star-rating-sm').eq(0).click()
        cy.wait(800)
        cy.get('a[data-name="In Stoc"]').click()
        cy.wait(800)
        cy.get('a[data-name="Cablu alimentare"]').click()
        cy.get('button > span').contains('Cele mai populare').click()
        cy.get('li > a').contains('Pret crescator').click({force:true})
        cy.wait(600)    
        cy.get('div[id=card_grid] > div').eq(0).click(100, 100)
        cy.get('button[data-test="main-add-to-cart-button"]').click()
        cy.get('a[data-test="atc-modal-cart-details"]').eq(0).click()
    })

})